// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_0CNFzHUBuvnAIcPakmKmdGHIbEG5Ng',
    appId: '1:880795176381:web:c6a34a43448cbf24d456d4',
    messagingSenderId: '880795176381',
    projectId: 'quizzle-demo-4c0cc',
    authDomain: 'quizzle-demo-4c0cc.firebaseapp.com',
    storageBucket: 'quizzle-demo-4c0cc.appspot.com',
    measurementId: 'G-C87ZVCFPDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgvghX-mL35zpCl6rzYVnZv3BvAWGavs',
    appId: '1:880795176381:android:a3cf94c80b82dd74d456d4',
    messagingSenderId: '880795176381',
    projectId: 'quizzle-demo-4c0cc',
    storageBucket: 'quizzle-demo-4c0cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5UR91oPoNMwm1VO5t5Oj_nU2G4XV97do',
    appId: '1:880795176381:ios:a038c65dddc00121d456d4',
    messagingSenderId: '880795176381',
    projectId: 'quizzle-demo-4c0cc',
    storageBucket: 'quizzle-demo-4c0cc.appspot.com',
    iosClientId: '880795176381-12dcc78k2f841jinnhgje12ue09m93st.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzledemo',
  );
}
